### ISSUE TITLE
Add analytics to admin dashboard

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1112]
Action Items (https://github.com/brave-intl/publishers/issues/1160):
- [x] Drive to get an api setup on analytics.brave.com
- [x] usage trends (all time - filter)
- [x] device trends (all time - filter) Will need to expose stats from analytics.brave.com 

Action Items:
- [x] Drive https://github.com/brave-intl/bat-ledger/pull/381
- [ ] Include top grossing (from ledger) to admin#home
- [ ] earning/paid (all time - filter))
