### ISSUE TITLE
(Brave Rewards) Donation Banner Polishing

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1179]
Master list:
Please create new issues and update below and fix as separate PRs to prevent duplicate work.

Blocker:
- [x] Include URLs for image uploads on production **Albert**
- [x] Unused strings specified in `app/javascript/locale/en.js` **Albert**
- [x] Limit image sizes **Albert**
- [x] Unlock NPM dependencies **Albert**
- [ ] Uniform image file size, resolution, and extension **Albert**

High Prio:
- [x] Re-selecting an image for upload doesn't work **Albert**

- [x] Indicate editable fields **Dan**

- [ ] Handle editing donation amounts better (e.g. deleting on donation amount results in NaN?) **Dan **

- [ ] Support Preview updated is updated after save as opposed to forcing a refresh to see the saved content.

- [x] Spacing and font size for initial modal menu. **Nick**

- [ ] Fix offset on initial modal menu.

- [ ] Add default selection on Brave Rewards

- [x] Handle deleting of images 
(Active Storage should handle this)

- [x] Make sure save doesn't re-save the same photo
Verified that this is in place

- [ ] Hard code currency daily. Ideally support currency changes live.

- [x] Darken background image **Dan assigned**

Medium Prio:
- [x] Add BRAVE_REWARDS_EMAIL_WHITELIST to `base.yml` **Nick assigned** - https://github.com/yachtcaptain23/publishers/pull/7

Lower Prio:
- [ ] Be able to handle errors from the controller. 
- [ ] Handle different image resolutions.

**Comment by dlipeles** [comment]
https://github.com/brave-intl/publishers/issues/1183

**Comment by dlipeles** [comment]
This iteration is closed, please see the continuation and improvement at #1214
