### ISSUE TITLE
Tipping Banner 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1214]
![0e3328c3-84ae-4e6b-b733-0b6625bfcea0](https://user-images.githubusercontent.com/4713771/46704925-2f900e80-cbfb-11e8-8b99-8d03278512fc.png)

#### Preview

- [x] Rework Preview -  Preview should exist outside of modal, it is intended to be a representation of the real banner. 

#### General Styling

- [x] Rework social links - Social links should be added sequentially and type selected from a drop down
- [x] Layout - More horizontal padding
- [x] Donations Jar + Branding - Should exist in top navigation of editing
- [x] Edit prompts on hover - Elements should indicate edit-ability on hover.
- [x] Restyle donation buttons - Buttons should contain bat logo, rework editing as click-to-edit
- [x] Font sizing on text - Headline text should appear larger

#### Per Channel Mode

- [x] Users can style each channel uniquely, or choose to use a single style across all channels

#### Intro Modal
- [x] Update intro modal - Add more content and style as specified

#### Update Notice
- [x] Update Notice - Upon saving, modal should pop up informing the amount of time to see updates, users choose to disable this. 

#### Images
- [x] Comprehensive Image Editing - Users should be able to crop and scale uploaded images.
- [x] Retina Support - Request 3x resolution images to support retina displays.
