### ISSUE TITLE
Refactor + Fine Details

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1289]
Tipping Banner has been through several revisions over a short period of time and the codebase is in need of a refactor to remove artifacts of old versions and improve maintainability. 

#### Refactor 
- [x] Remove code artifacts from old versions
- [x] Move JSX markup into separate component files
- [x] Find a better solution to loading than using timeout, possibly `async/await` on image cropping.
- [x] Consolidate `handleDone` and `cropFetchedLogo` into one function
- [x] Move all styles into separate file
- [x] Use arrow functions to replace `this.method.bind(this)` functions

There are also several areas that need fine details updated to become consistent with the design spec. 

#### Fine Details
- [x] `Same banner content` toggle in upper right corner
- [x] Add `Done` button instead of cancel `x` 
- [x] Smaller margins between text fields, revise font size and weight
- [x] Improve links area by fitting to row
- [x] Tipping buttons should be smaller and aligned to `Set tipping amounts`
- [x] Image cropping section should appear as a second modal

**Comment by dlipeles** [comment]
cc @jenn-rhim 

Agree with many of your points from our conversation last week. Was hoping I could ask a few clarifying questions 

#### Removing the `x` button from modals

I can do this, and add a `Done` button in the control bar of Tipping Banner, but I have a few questions on consistency here. It seems like some modals are designed to have an `x` while other don't, see:

![screen shot 2018-10-29 at 1 04 24 pm](https://user-images.githubusercontent.com/4713771/47667640-e3424980-db7c-11e8-857c-3eabebea8fe3.png)

![screen shot 2018-10-29 at 1 05 41 pm](https://user-images.githubusercontent.com/4713771/47667696-053bcc00-db7d-11e8-84ff-140fed45e2ed.png)

while these modals will not have an `x` 

![screen shot 2018-10-29 at 1 19 41 pm](https://user-images.githubusercontent.com/4713771/47667832-53e96600-db7d-11e8-8dc5-547193c8a993.png)

![image 2](https://user-images.githubusercontent.com/4713771/47667841-59df4700-db7d-11e8-8447-34b8c5ea7a5a.png)

Can you comment on this Jenn? I think the goal would be to remove the `x` from all modals, but I just want to make sure that whatever we choose will be consistent across all modals. 

#### Cropping Modals & Mobile Responsiveness

This will take some work, but I can implement the cropping feature as a second modal. 

The reason I chose animations originally was because I am looking at mobile users. As it stands modals are already difficult for mobile users, adding a second modal will make usability impossible for mobile. 

Details [here](http://uxmovement.com/mobile/why-you-should-avoid-using-modal-windows-on-mobile/)

This is okay, as long as we `create a separate flow for mobile users`. Is this something we can do later on? 

Thanks so much Jenn, I am looking to add much of your feedback into the code, but I think it's a good idea to talk about these things too.

**Comment by jenn-rhim** [comment]
@dlipeles The answer is not that clear cut unfortunately. Web UI created various conventions that made it hard. But the transactional modal dialog typically requires user to answer a question in order for the system to move forward. This type of dialog should provide a button to proceed and a button to cancel out the action the user asked for explicitly. A lot of the confirmation dialogs or editing dialogs belong to this category and even though you can use X for cancel, clarity for the user is recommended and better for the usability. Dialogs where it's suitable to use X for dismissing them are information only, starting of something new that either 1. dismissing them with X is non-consequential, 2. design intent promotes the proceeding button without cluttering it with cancel button. Typically the dialog that can be dismissed with X is also the dialog that the user can dismiss it by clicking outside of the dialog. Hope this helps. All of the dialogs above examples are correct, except 'Use current banner for all channels?' dialog should not have x.

**Comment by dlipeles** [comment]
@jenn-rhim Thanks for the detailed response Jenn, and I appreciate you taking a call with me about this too. I'll follow your guidelines for this web UI. To make it simple here, we'll just be adding the 'x' button for the `intro modal` where it is non-consequential, all other modals in this feature will not have the 'x'. In other features with modals we will make that decision on a per-modal basis as you mentioned. 
______________

I'd like to get your thoughts on mobile responsiveness too. As it stands right now, the vast majority of visitors to our site will be on desktop devices, so the current implementation should satisfy. 

However, mobile devices are growing in market space and we'd do well to provide mobile users an easy-to-use flow for setting up their banners. My take would be we need to present the components to mobile users `one item at a time` to prevent cluttering their device. Animations might be useful here, but I'd really like to get your take on this Jenn. Thanks!

**Comment by dlipeles** [comment]
Closed in #1316
