### ISSUE TITLE
Improvements for Admin Dashboard 

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1436]
Feature for all:
- [x] Have CSV dumps
- [ ] Have aggregate data at the top e.g. Channel count, verified channel count.

Channels List
- [ ] add date created column
- [ ] make channel identifier clickable link to channel
- [ ] make columns click-sortable
- [ ] Default sort is by date joined, reverse (newest first)
- [ ] Show number of subscribers where possible
- [ ] Show number of referred downloads

Publishers List:
- [x] add date joined
- [x] make columns click sortable
- [x] default sort is by join date, reverse order (newest first)
- [x] add column for number of channels
- [x] column for date last logged into dashboard would be awesome
- [ ] amount paid out to date
- [ ] amount paid out for last settlement

Payout Reports:
- [ ] Add CSV download (for excel)

Unclaimed amounts on contributions:
- [ ] Get details for non-verified channels. Right now Top Publisher Contributions is only for verified channels.

**Comment by corymcdonald** [comment]
Going to close this issue, there are always going to be improvements for the admin dashboard, a lot of these are ported over to Metabase now. 😄
