### ISSUE TITLE
Integrate SiteBannerEditor with brave-ui & Polishing 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1452]
Seeing the big picture with Publishers 2.0 UI, we can also start integrating our legacy UI with brave-ui. 

#### brave-ui integration
- [ ] Consolidate all files into 
```
     - siteBannerEditor/
        --assets/
           ---defaultCoverImage.svg
        --index.ts
        --spec.ts
        --style.ts
```
- [ ] Convert `.jsx` to `typescript (.ts)`
- [ ] Create tests using `jest` in `spec.ts`
- [ ] Extract server fetching logic, aim for a prop passing flow (while retaining single page functionality)

#### Polishing 

- [ ] Right-align tip amounts in dropdown (might need PR to brave-ui dropdown) 
- [ ] Rework social link selection and addition UI 
- [ ] Signal recommended image resolution to users & add this info to Publishers doc 
- [ ] Ensure conversion rates are correct, and reflect current user's currency choice
- [ ] Ease in highlight effect when selecting Text Area (use Coinbase for reference) 
- [ ] Use better default cover image
- [ ] Show publisher's first initial if logo not set
- [ ] Allow full toggle animation before loading screen

**Comment by dlipeles** [comment]
Closed as this will be addressed in UI 3.0
