### ISSUE TITLE
Site Banner - QA 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1465]
#### Need to patch Site Banner Editor with fixes for issues found in QA

- [x] Refresh on Stale Session , We need to render some UI when the session is expired prompting the publisher to log in again, then redirect them to the login page 

- [x] Widen Social Link display, social links are too long for the display and the ('x') to delete them is missing

- [x] Fix Social Link dropdown, on the third social link added the dropdown is partially hidden

- [x] Return from Preview , When returning from preview the previously entered values disappear, we need to pass them as a prop when returning from preview. 

- [x] Fix Missing 'X' on intro modal, When opening the intro modal for a second time, the 'x' in the corner is missing. 

- [x] Decide between 'X' or 'Close Preview' Button in preview, currently rendering both. 

- [x] Fix unnecessary scroll bars #1447 

 - [x] Tips not persisting to Browser

**Comment by kjozwiak** [comment]
When you already have two links set via the `social media` feature, pressing on the down button will expand the list which will be cut off. Example of the list being cut off:

<img width="341" alt="screen shot 2018-12-18 at 4 51 59 pm" src="https://user-images.githubusercontent.com/2602313/50185261-4fbc0800-02e5-11e9-935f-c819fac994d1.png">

If you scroll down, the drop down spills over outside the modal. Example:

<img width="381" alt="screen shot 2018-12-18 at 3 40 08 pm" src="https://user-images.githubusercontent.com/2602313/50184148-2f3e7e80-02e2-11e9-8742-45b2a2b6d0f3.png">

Not the end of the world but might confuse some users who don't realize that they need to scroll down to view the other choices if they already have a few links set.

**Comment by kjozwiak** [comment]
There's currently no way to revert the images to the default template. If someone sets an image and than decides they want to revert back to the original template, there's no way of doing that. The user is basically stuck with the images they've uploaded or they need to upload another image to replace the old ones. We should have a "revert to default template" button somewhere on the website.

<img width="1399" alt="screen shot 2018-12-18 at 3 43 07 pm" src="https://user-images.githubusercontent.com/2602313/50185438-c5c06f00-02e5-11e9-978e-9ca8b0adef9e.png">

**Comment by corymcdonald** [comment]
I'd say low priority but if you try to add like 2 youtube channels it just replaces the older one. It might make sense to have the select list change based on what channels you have pre chosen

**Comment by dlipeles** [comment]
@corymcdonald I think at this time we only wanted to support 1 channel for each type, but we should expand this in the future

**Comment by kjozwiak** [comment]
Was about to add the same thing re: only being allowed to one link per social media site. But wasn't 100% sure if this was expected.

**Comment by kjozwiak** [comment]
Seems like the custom tipping amounts are not being reflected in the browser. All other changes are appearing in the banner other than the custom tipping amounts. Quick example:

Here's how my current preview looks when logging into the Publishers website (notice the different tipping values that I selected from the drop down):

<img width="1407" alt="screen shot 2018-12-18 at 11 15 34 pm" src="https://user-images.githubusercontent.com/2602313/50232500-17690800-037f-11e9-801d-9f2c11e8ecbe.png">

Here's how my banner looks when visiting kjozwiak.github.io (notice the tipping not changing)

<img width="1404" alt="screen shot 2018-12-18 at 11 13 24 pm" src="https://user-images.githubusercontent.com/2602313/50232531-2e0f5f00-037f-11e9-8a26-4b93968dfaf8.png">

I'm not sure if this is an issue with the browser or Publishers though. @dlipeles if you're not sure, please work with @NejcZdovc to figure out of it's something Publishers related or client related.

**Comment by dlipeles** [comment]
@kjozwiak Hi Kamil, in the case of tipping it is client related, I can see from our payload that we are serving the correct tip amounts. 

Let me follow this up with @NejcZdovc

**Comment by NejcZdovc** [comment]
@dlipeles we don't yet have custom amounts in browser. We waited until we decided what to do with how they will be done. Now that this is defined (they will be predefined) we can implement it.

**Comment by NejcZdovc** [comment]
Issue created: https://github.com/brave/brave-browser/issues/2645

**Comment by dlipeles** [comment]
@NejcZdovc Super, thank you.

**Comment by kjozwiak** [comment]
Awesome, thanks @NejcZdovc & @dlipeles 👍

**Comment by kjozwiak** [comment]
I'm not 100% sure if this is an issue, but I expected my custom banner to appear whenever viewing my channels but ran into the following situation:

Seems like `https://www.youtube.com/channel/UCcYCtVuEvlaW7aFB6-eOY7A` is correctly showing my custom banner:

<img width="1825" alt="screen shot 2018-12-20 at 2 28 16 am" src="https://user-images.githubusercontent.com/2602313/50270486-b9303980-03ff-11e9-9d8c-89f78f50a776.png">

However, `https://www.youtube.com/channel/UCcYCtVuEvlaW7aFB6-eOY7A?view_as=subscriber` is showing me the following banner:

<img width="1809" alt="screen shot 2018-12-20 at 2 27 57 am" src="https://user-images.githubusercontent.com/2602313/50270516-cd743680-03ff-11e9-9555-f88e36a8e6e4.png">

**Comment by kjozwiak** [comment]
When you have `Same banner content for all channels` switched off so each channel has their own custom banner, clicking on `Save Changes` only saves the banner that you're currently viewing instead of everything. Here's a quick example of what happened to me:

* logged in and disabled `Same banner content for all channels` so each website has their own banner
* edited all four banners and clicked on `Save Changes`

Noticed that only one website was saved (the one I was viewing) and all the other changes were lost. Quick Example:

![publisherissue](https://user-images.githubusercontent.com/2602313/50272310-5641a100-0405-11e9-8d63-7166c45b0495.gif)

**Comment by dlipeles** [comment]
@kjozwiak Hi Kamil, thanks for this feedback, in these cases the banner is functioning as designed, but I agree that the design may cause some confusion to users. 

There is a proposed rewrite that will take place at a later date #1452 where we can address some of these things you mentioned, I'll need to get Jenn to agree to any design changes but I will be sure to talk about

* ```Toggle state should not save until Save Changes is clicked```
* ```Store the state of all banners simultaneously, instead of just the current banner```
* ```Add functionality to delete current image``` (Need Jenn to design the UI for this)
* ```Add button to clear banner to default``` (Possible, would need Jenn's approval)

**Comment by dlipeles** [comment]
@kjozwiak Please feel free to open a new item in Publishers if you see any issues not already discussed in this thread. Thanks so much for working with us 👍
