### ISSUE TITLE
[Master Issue] Account Summary Changes

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1741]
Tips will be split from auto-contribution. Will need to break this down into sub-issues.

Action Items:
- [ ] Support new balance reporting API and reflect in the GUI
- [ ] Support new transactions API and reflect in the GUI
- [ ] Changes to the Payout Report (details to be followed up later)

**Comment by yachtcaptain23** [comment]
Partially blocked by https://github.com/brave-intl/internal/issues/103 and https://github.com/brave-intl/internal/issues/102

**Comment by yachtcaptain23** [comment]
Removing from Gemini Milestone

**Comment by yachtcaptain23** [comment]
Tackled by settlements. Closing.
