### ISSUE TITLE
Update Admin Dashboard 💼 

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1743]
#### Motivation
We wish to improve the level of detail and readability on the admin dashboard. Additionally we need to create a more detailed paper trail regarding the suspension/unsuspension of publishers. 

#### Goals
- Better organization of detail on Publishers.
- Require evidence for the suspension + unsuspension of Publishers. (Paper trail)
- Enhanced Publisher notes , with threads

#### Implementation 
---

#### UX
- [x] Improve UX and details of Admin Dashboard #1745

#### Notes 
- [x] Improve the Admin Dashboard notes system #1746

#### Suspended Publishers Paper-Trail

- [x] Log e-mails from suspended publishers #1747

#### Additional Info
---

#### Blocking items:
- [ ] API for paid-to-date. You might want a breakdown for settlements.
- [ ] `suspended-publisher@brave` email list (probably assign to Asad to create this) 
- [ ] Store emails as notes (Might need webhook. Might need to support HTML in PublisherNotes)

#### Action Items:
- [ ] Service for fetching Youtube information just based on channel 
- [ ] Add retention chart for past 6 months (probably can just copy from home dashboard)
- [ ] Show potential payout
- [ ] Show downloads/installs/confirmations
- [ ] Show total contributions
- [ ] Show if the publisher was ever suspended and highlight and bold with a red colored font if it did occur
- [ ] Chart to show past 6 months of contributions, split by grants vs. user funds
- [ ] Make notes for suspending and unsuspending required
- [ ] Ask Ross for help on making #show look better
