### ISSUE TITLE
[Master Issue] BAT Points

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2216]
Oct 1
- [x] Locale ( https://github.com/brave-intl/publishers/issues/2186 )

Oct 15
- [ ] Stripe account integration (similar to Uphold or replace Uphold in the UI)
- [x] ~Storing region (https://github.com/brave/devops/issues/1804)~
- [ ] https://github.com/brave-intl/publishers/issues/2282

**Comment by yachtcaptain23** [comment]
Merged
