### ISSUE TITLE
Rails 6 Testing checklist

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2323]
Some changes were made that affected ActiveStorage quite a bit, so this is the checklist

- [ ] Brand new site banner
- [x] Can upload a new logo
- [x] Can upload a new background image
- [x] Case info upload
- [x] Sign in to publishers
- [x] Sign in to admin
- [ ] V1/V3 channels API gets built and is responsive

# Test Plan

### New Publisher
- [x] 1. Sign up with an email address that hasn’t been used before
- [x] 2. Click the email link to login
- [x] 3. The home page loads correctly

### A publisher can add channels

- [x] 1. On the homepage the publisher can click the "Add channel" button
- [x] 2. The publisher can register their OAuth property (Youtube, Vimeo, Twitch, etc)
- [ ] 3. Publisher can register a website and it be verified
- [x] 4. Publisher's failed verification show up on the homepage 

### New publisher can connect uphold

- [x] 1. As the new publisher add a few channels
- [x] 2. Connect Uphold
- [x] 3. Select a default currency
- [x] 4. A card should be created for the publisher under the account

### A user can disconnect and reconnect Uphold

- [x] 1. Go to the user’s uphold cards list
- [x] 2. Disconnect Uphold
- [x] 3. Reconnect Uphold
- [x] 4. Ensure that if the same currency is selected another card is not created

### A user can change their default currency
- [x] 1. On the publishers dashboard click “Change default currency”
- [x] 2. Select a unique default currency like LTC / DASH / UPBTC, etc. 
- [ ] 3. Go to the Uphold cards page and ensure a “Brave Rewards” card was created for the specified currency

### When a publisher changes their uphold password

- [ ] 1. Log into uphold
- [ ] 2. Change your password
- [ ] 3. Log into Publishers
- [ ] 4. Should be presented with a “Re-authorize” button

### A publisher can change their email

- [x] 1. On the dashboard click on "Edit contact"
- [x] 2. Enter a new name, press save
- [x] 3. Refresh page to ensure it saved
- [x] 4. Enter an email, ensure it sends an email to the new account
- [x] 5. Sign out of Publishers
- [x] 6. Click Confirm on the new email 

### A publisher can set their session active for 30 days

- [x] 1. Click on Settings on the profile dropdown
- [x] 2. Click on the toggle
- [x] 3. Confirmation is shown to the user
- [x] 4. Refresh the page
- [x] 5. Setting is marked as active

### A publisher can make changes to their Site Banner

- [x] 1. A user can go onto the Site Banner and make changes to the text.
- [x] 2. A user can upload an avatar
- [x] 3. A user can upload an background
- [x] 4. Refresh the page
- [x] 5. Click on Site Banner to ensure that the images and changes saved.

### A publisher can download view their Statements

- [ ] 1. Log into the publishers dashboard
- [ ] 2. Click on “Statements”
- [ ] 3. The page works 

### A publisher in no grants can view their homepage

- [x] 1. Set the existing publisher to "No grants"
- [x] 2. Login and notice the UI change, go to the appeals workflow by clicking on the link in the balance
- [x] 3. Create a new case, upload files
- [x] 4. User can post comments and attach files
- [ ] 5. The admin can view the cases and the files

### A suspended publisher can login and view the message

- [x] 1. Set the existing publisher to "Suspended"
- [x] 2. Go to multiple different urls like /publishers/home, /publishers/statements, ensure redirect working

### You can view publishers
- [x] 1. Click on a publisher who has connected their uphold account
- [x] 2. Go to another publisher account which isn’t uphold connected, the page still loads
- [ ] 3. Go to a publisher who hasn’t signed in. The page still loads

### Payout report is equivalent
- [x] 1. Compare the payout report that was previously generated
- [ ] 2. Ensure the contents are equal (minus minor amount changes)

### An overview of countries for Publishers is shown

- [x] 1. Click on the publishers statistics page 
- [x] 2. A table which populates the list of countries in which we have publishers is populated

**Comment by yachtcaptain23** [comment]
Closing due to merge https://github.com/brave-intl/publishers/pull/2326
