### ISSUE TITLE
Master Issue: UI for Publisher Ads consent and TOS Changes

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2423]
Reference: https://docs.google.com/document/d/1Q4NJKotgwCIdKu0DmFhW56vzKSh-wbGPDnc82IUqsf8/edit#

Landing page P1
- [x] UI: New create a new account flow
- [x] Store record of the time of agreement
- [x] Store versioning of the TOS (Can check against the date)
- [ ] Inform what we do in the email (this is tackled above by the UI)
- [x] Not pre-checked
- [x] Cannot register unless checked

Other:
- [x] Copy templates to Sendgrid P2
- [ ] TODO: Update email footer requirements

Publisher Ads (P1, after Landing Page)
- [ ] Check for allowing Brave to serve ads on website for new website registration
- [ ] Show check in the channels list
- [ ] Add 'Learn More' popup

In-app re-permissioning
- [ ] TODO
