### ISSUE TITLE
Tracking issue for email scenarios

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#341]
We have a new email api and have a number of scenarios which we wish to handle. 
To keep these scenarios organized a new tracking issue and label are sufficient.

The original issue is here : https://github.com/brave-intl/publishers/issues/7

# Scenarios:
### Cold Call
- [ ] Threshold met for YouTube Channel - https://github.com/brave-intl/publishers/issues/372
- [ ] Threshold met for Site Publisher - https://github.com/brave-intl/publishers/issues/375
### Process
- [ ] Contact email changed for YouTube Channel or Domain - https://github.com/brave-intl/publishers/issues/423
- [ ] Sign up
- [ ] Login
- [ ] Email Verified
- [ ] Oauth Verified
- [ ] Site Verified
- [ ] Channel Verified
- [ ] Settlement Occurred
- [ ] Verification Stalled
- [ ] Statement Ready
- [ ] Uphold wallet not created - https://github.com/brave-intl/publishers/issues/320
- [ ] Contention Settled
- [ ] Bitcoin publisher converted to BAT
- [ ] Email change verified - https://github.com/brave-intl/publishers/issues/430
### Error
- [ ] Verification failed - Wordpress
- [ ] Verification failed - Github
- [ ] Verification failed - DNS
- [ ] Verification failed - well-known text
### Campaign / Social Marketing
- [ ] Publisher winback email - https://github.com/brave-intl/publishers/issues/431
- [ ] YouTube channel promotion
- [ ] Distribute 'support' badge for acquisition for YouTube Channel
- [ ] Distribute 'support' badge for acquisition for Site Publisher

**Comment by yachtcaptain23** [comment]
Spoke with Alex, he's fine with closing.
