### ISSUE TITLE
[WIP] Dashboard: Show graph of referrals over time

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#487]
(This depends on #466. We will launch with #466 and ship this afterwards.)

To help publishers see their audience's engagement with the referral promo, let's update the dashboard to include a graph showing:
- X-axis: Day
- Y-axis: Count
  - Series 1: Referral downloads per day
  - Series 2: Referrals completed*
    - Persons who downloaded brave and are still active 30d later

We should also concisely explain that referral downloads complete when they've been using Brave for at least 30 days.

### Graphing library:
https://github.com/frappe/charts could work. it's relatively lighter than other graphing libs -- 50 KiB min.

### (TBD) Promo API endpoints

Tracked in https://github.com/brave/vault-promo-services/issues/3
```
// Get aggregated referrals over time for an owner -- times in UTC
GET {promo-api}/api/1/promo/owners/{ownerId}/statsByTime
{
  times: ["2018-01-01", "2018-01-02", ..., "2018-01-31"]
  series: [
        {
            name: "downloads",
            values: [25, 42, ..., 0]
        },
        {
            name: "referrals / TBD",
            values: [0, 0, ..., 10]
        }
    ]
}
```

**Comment by ayumi** [comment]
@jenn-rhim design will be appreciated for this!
not urgent -- we'll work on this right after Referral Promo launches.

**Comment by nvonpentz** [comment]
- [x] Total owner stats displayed on the dashboard in promo panel
- [ ] Channel specific stats
- [ ] Graphing of downloads

**Comment by nvonpentz** [comment]
Until further notice, we will not be implementing this.
