### ISSUE TITLE
2FA auth flows cleanup

### ISSUE THREAD

**Issue by mixonic** [brave-intl/publishers#551]
Mostly followup to https://github.com/brave-intl/publishers/pull/523

* [x] Use the proper flash style for TOTP errors to make them appear as warnings. (https://github.com/brave-intl/publishers/pull/559)
* [x] Ensure the "security key unsupported" headline is not inside the small column. (https://github.com/brave-intl/publishers/pull/562)
* [x] Middle align error messages when they are a single line (https://github.com/brave-intl/publishers/pull/559)
* [x] If user has U2F and TOTP but no U2F support change the message to: "Your preferred method of two-factor authentication is security key. But it's not supported by your current browser. Switch to Google Chrome or Opera or login using authentication code below." (https://github.com/brave-intl/publishers/pull/562)
* [x] If user has U2F and no TOTP, but no U2F support change the message to: "Switch to Google Chrome or Opera to log in. We recommend setting up authenticator app as a backup method for two-factor authentication for this situation." and the title to "Security key not supported by your browser." (https://github.com/brave-intl/publishers/pull/562)
* [x] Migrate our flash message type options to: `alert -> red` `warning -> yellow` `notice -> blue`. Yellow is new, use the mock below for it an its icon. Update the docs and existing messages. Remove the green state entirely. (https://github.com/brave-intl/publishers/pull/559)

I'll need a few things from @jenn-rhim 

* [x] ~Regarding the unsupported screens on https://github.com/brave-intl/publishers/pull/523 you said "yellow is fine, but we need the warning icon (!)" - I'll need a mock to proceed. I'm concerned that the text in that yellow box would then be extremely narrow and difficult to read.~ After the mock below was added @jenn-rhim and I discussed this over Slack. She is going to mock up the two use cases in detail: a) The user has security key and code, but their browser does not support the key. b) The user only has security key, but their browser does not support the key. (https://github.com/brave-intl/publishers/pull/571)

**Comment by jenn-rhim** [comment]
@mixonic sent the sketch file over slack...

here is the screenshot.

![20-2fa-unsupportedbrowser](https://user-images.githubusercontent.com/4369856/35530179-27f22da0-04e8-11e8-89f3-c01e9cd0c7c5.png)

**Comment by jenn-rhim** [comment]
@mixonic  2 cases:

1. key unsupported browser/totp has set up:
![image](https://user-images.githubusercontent.com/4369856/35541764-340abd5e-0511-11e8-960e-03bb474a5e41.png)


2. key unsupported/totp has not been set up:
![image](https://user-images.githubusercontent.com/4369856/35541761-2fb400b2-0511-11e8-9efe-f094dd5801df.png)
