### ISSUE TITLE
Port dashboard styles to bootstrap 4

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#786]
We are currently using the legacy bootstrap 3 styles for the dashboard.  We should port these to use bootstrap 4 like the rest of the site.  Here's a [cool guide](https://blog.201-created.com/using-and-migrating-to-bootstrap-4-on-rails-21aea99b4ba) I found. 😉

![image](https://user-images.githubusercontent.com/12549658/38701463-ebc3faee-3e6b-11e8-99c5-703c6b97ff97.png)

### Update
TO DO
- [ ] Create new dashboard: html elements + styles
- [ ] Update dashboard js to use new DOM
- [ ] Integrate with other boostrap 4 styles
