### ISSUE TITLE
June priorities

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#921]
Creating an umbrella issue that we need to prioritize;

For June 6 timeline (BAT hardening projects)
- [x] Need to add (Settlement date = 8th of next month) "Next payment occurs 8th of month XX" Tracking in https://github.com/brave-intl/publishers/issues/923
- [ ] BAT contribution == only settled downloads (no other value is definite and should not be included)
- [ ] Statements should reflect all events (downloads, confirmed-downloads, attention-based-payments) Tracked in https://github.com/brave-intl/publishers/issues/542
- [x] Default currency is BAT fix should be reflected and done before settlement happens -- new and existing users. Tracked in https://github.com/brave-intl/publishers/issues/835

Post June 6 (immediate priority)
- Redo Dashboard (Jenn has posted the fixes) -- this is related to the javascript topic

@yachtcaptain23 @evq @nvonpentz @jenn-rhim 

@jenn-rhim - for the June 6 fixes, do you want to recommend text, etc?  I am happy to drive it but "Next payment occurs 8th of XX" is fairly clear

**Comment by yachtcaptain23** [comment]
@mandar-brave , With regards to the fields in the statements CSV:

```
counts contains the confirmed downloads
eyeshade doesn't have the total download count info
```

I'll share with you the CSV example privately.
